deployfolder: _site
verselimit: 100000000000
booknames:
  en: ["Genesis", "Exodus", "Leviticus", "Numbers", "Deuteronomy", "Joshua", "Judges", "1 Samuel", "2 Samuel", "1 Kings", "2 Kings", "Isaiah", "Jeremiah", "Ezekiel", "Hosea", "Joel", "Amos", "Obadiah", "Jonah", "Micah", "Nahum", "Habakkuk", "Zephaniah", "Haggai", "Zechariah", "Malachi", "Psalms", "Proverbs", "Job", "Song of Songs", "Ruth", "Lamentations", "Ecclesiastes", "Esther", "Daniel", "Ezra", "Nehemiah", "1 Chronicles", "2 Chronicles"]
navigreminder:
  en: '<br>To navigate back- and forwards, use the arrow keys <span class="shadow">←</span> and <span class="shadow">→</span> on your keyboard'
sitename:
  en: Biblical Hebrew for linguists
sitesubname:
  en: Westminster Leningrad Codex
largedescription:
  en: Biblical Hebrew samples for linguists. Verses, phonetics, gloss translation, morphology codes, syntax trees.
words:
  back:
    en: Back
  forth:
    en: Forth
  gloss_header:
    en: Gloss translation
  syntax_header:
    en: Syntactic structures
  heading_part1:
    en: Law
  heading_part2:
    en: Prophets
  heading_part3:
    en: Writings
  
